[project]
name = "mmdet3d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black==20.8b1",
    "codecov>=2.1.13",
    "flake8>=5.0.4",
    "interrogate>=1.7.0",
    "isort>=5.13.2",
    "kwarray>=0.6.16",
    "lyft-dataset-sdk>=0.0.8",
    "networkx>=2.5",
    "numba>=0.58.1",
    "numpy>=1.23.5",
    "nuscenes-devkit>=1.1.9",
    "parameterized>=0.9.0",
    "plyfile>=1.0.3",
    "pytest>=8.3.5",
    "pytest-cov>=5.0.0",
    "pytest-runner>=6.0.1",
    "scikit-image>=0.20.0",
    "tensorboard>=2.13.0",
    "trimesh>=4.7.1",
    "typing-extensions>=4.14.1",
    "ubelt>=1.3.7",
    "xdoctest>=0.10.0",
    "yapf>=0.43.0",
]
