[project]
name = "eloss-stable-information-flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "albumentations>=2.0.8",
    "asyncio>=3.4.3",
    "flake8>=7.3.0",
    "imagecorruptions>=1.1.2",
    "isort>=6.0.1",
    "matplotlib>=3.10.3",
    "mmcv>=2.2.0",
    "mmdet>=3.3.0",
    "mmengine>=0.10.7",
    "numpy>=2.3.2",
    "open3d>=0.19.0",
    "opencv-python>=4.11.0.86",
    "openmim>=0.3.9",
    "pandas>=2.3.1",
    "pillow>=11.3.0",
    "plyfile>=1.1.2",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "scikit-learn>=1.7.1",
    "scipy>=1.16.0",
    "terminaltables>=3.1.10",
    "torch>=2.7.1",
    "torchaudio>=2.7.1",
    "torchvision>=0.22.1",
    "trimesh>=4.7.1",
    "yapf>=0.43.0",
]
